services:
  currency-conv:
    image: git.ferret-tyrannosaurus.ts.net/kaijubee/currency-conv:latest
    restart: always
    user: 1001:100
    read_only: true
    environment:
      - OPEN_EXCHANGE_RATES_APP_ID=${OPEN_EXCHANGE_RATES_APP_ID}
      - PASSWORD=${PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.currency-conv.rule=Host(`currency-conv.nas.phoebe.codes`)
      - traefik.http.routers.currency-conv.entrypoints=websecure
      - traefik.http.services.currency-conv.loadbalancer.server.port=3000

networks:
  default:
    name: proxy
    external: true
